### PR TITLE
Upgrade eSpeak-ng to latest master

### PR DESCRIPTION
**Pull request by michaelDCurran**
### Link to issue number:
None.

### Summary of the issue:
With the merging of #7846, NVDA users complained of several issues in espeak-ng:
* espeak-ng/espeak-ng#523: Macedonian spoke junk characters after each string, and 0s before speaking each character.
 * espeak-ng/espeak-ng#520: issues speaking in Serbian
* espeak-ng/espeak-ng#518: Bad pronounciations in bulgarian

### Description of how this pull request fixes the issue:
Upgrade to latest master of espeak-ng which addresses these issues.

### Testing performed:
* Ran NVDA with this version of eSpeak-ng. 
* espeak-ng now has tests which should cover these kinds of breaks in the future.

### Known issues with pull request:
None.

### Change log entry:
Upgrade to espeak-ng commit xxxx

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi michael,
Do we have any compilation errors in the espeak NG itself? i.e. some phonemedata cannot be generated properly?
if not, i suggest merging it to master for further testing of all slavic language branches...

**Comment by michaelDCurran** [comment]
To @zstanecic, @nidza07 and k-kolev1985:
Please test the following try build of NVDA with latest espeak-ng master: https://ci.appveyor.com/api/buildjobs/e3c2cb43cjtd26pf/artifacts/output%2Fnvda_snapshot_try-latestEspeak-15686%2C0f0916a7.exe
Let me know if there are still regressions in eSpeak-ng from what is in NVDA 2018.2.

**Comment by zstanecic** [comment]
Hi michael,
I can confirm, that all bugs are gone in this build of espeak NG.
I have tested bulgarian from the sample text of stoyan stoyanov, Gramatika na balgarskiot ezik
for macedonian i used a sample text from the website of macedonian radio television. i tested the simple characters, too!
the macedonian, as well as bulgarian, serbian and bosnian are now fixed.all palatalisations which were present are now gone.
@michaelDCurran 
best,
Zvonimir

**Comment by zstanecic** [comment]
btw, on new thing for macedonian, is added transliterated text reading
so all text romanized in the british manner, but written in macedonian will be read

**Comment by k-kolev1985** [comment]
@michaelDCurran I've tested a little bit and I can confirm that the wrong pronunciations in bulgarian are fixed in the test build.

**Review by LeonarddeR — APPROVED** [review]
> espeak-ng now has tests which should cover these kinds of breaks in the future.

Could we somehow run these tests within our test suite?

**Comment by michaelDCurran** [comment]
I guess we can look into this, but  at first glance it looks as though 
we'd need to use their makefiles and also compile the espeak-ng 
executable itself, which NVDA doesn't need at the moment.
I will research this further.
