### PR TITLE
More conservatively add EditableText support to UIA objects

### LINKED ISSUE #18399: At least with Braille, object navigation throws errors in XAML apps, like WhatsApp
### Steps to reproduce:
1. Open WhatsApp desktop
2. Use laptop:nvda+shift+left arrow to object nav backwards several times.

### Actual behavior:
Ad some point, e.g. for objects like `Chats`, `End to end encrypted`, the following is logged:

```log
ERROR - eventHandler.executeEvent (10:49:13.254) - MainThread (4452):
error executing event: becomeNavigatorObject on <NVDAObjects.Dynamic_XamlEditableTextEditableTextWithAutoSelectDetectionUIA object at 0x0AB429B0> with extra args of {'isFocus': False}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1398, in event_becomeNavigatorObject
  File "braille.pyc", line 3119, in handleReviewMove
  File "braille.pyc", line 2961, in _doNewObject
  File "braille.pyc", line 2261, in getFocusRegions
  File "braille.pyc", line 1551, in update
  File "NVDAObjects\UIA\__init__.pyc", line 1114, in compareEndPoints
AttributeError: 'NVDAObjectTextInfo' object has no attribute '_rangeObj'
```

### Expected behavior:
No errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-37061

#### Windows version:
24H2

#### Name and version of other software in use when reproducing the issue:
WhatsApp 2.2524.4.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #18399 
Fixup regression caused by #18271

### Summary of the issue:
Since #18271, object navigation might cause errors with braille in XAML static text controls.

### Description of user facing changes:
No errors, working braille.

### Description of developer facing changes:
N/a

### Description of development approach:
Be more conservative in applying an EditableText overlay class to UIA objects. Before this change, objects only needed to have UIATextInfo, implicitly meaning that it ought to have a text pattern. With this, we only add EditableText if either:
a. The object has navigable text; or
b. The objects text pattern reports that selection is supported.

### Testing strategy:
Tested str from #18399 

### Known issues with pull request:
I can't think of any reason why this is too conservative. May be in severely broken TextPattern implementations that don't implement `SupportedTextSelection`. I only just discovered this property.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks. I think the impact is the same, but I'm wondering whether it makes more sense to restrict when we use EditableText, rather than restricting when we use UIATextInfo. That is, I think it is wrong to say "this object is editable text" when it clearly isn't. On the other hand, the TextInfo isn't a statement of behaviour; it's a statement of support. It isn't saying "this is editable"; it's saying "this supports querying text", which it does. We might choose not to use it, but it still supports it. Keeping the TextInfo means that something *could* use makeTextInfo if it wanted to. It's then a higher layer decision to choose whether to use it or not.

I still wonder whether this is a risky change given that we're touching things that have been thus for 16 years. :)

**Comment by jcsteh** [comment]
Reducing when we use EditableText is also probably slightly less risky than altering TextInfo.

**Comment by LeonarddeR** [comment]
Makes sense to me. I reworked this pr accordingly.

**Review by seanbudd — APPROVED** [review]
