### PR TITLE
fix installation crash from StaticBoxSizer changes

### LINKED ISSUE #12196: NVDA Alpha 22012: installation aborts unexpectedly
With NVDA Alpha 22012, attempting to move past the License agreement in the Installation dialog by ticking the I Agree check box and selecting the Install NVDA on this computer button results in the unexpected closure of the installation wizard.
### Steps to reproduce:
1. Run NVDA Alpha 22012 installer.
2. Tick the I agree check box.
3. Select the Install on this computer button.
### Actual behavior:
The installation wizard aborts and NVDA keeps using the temporary copy it has generated until it's closed and restarted.
### Expected behavior:
The next Installation wizard window should come up to allow installation to continue.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Currently running NVDA Alpha 21882, and trying to install NVDA Alpha 22012
#### Windows version:
Win 10 Pro 64-Bit, Version 20H2 (OS Build 19042.867)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alpha 21895 can be installed successfully, but I haven't tried alphas between 21895 and 22012.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Closes #12196

### Summary of the issue:

The standard installation process crashes with the following traceback, likely caused by #12181

```
ERROR - unhandled exception (11:07:36.839) - MainThread (19656):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 831, in <lambda>
  File "gui\__init__.pyc", line 861, in onAction
  File "gui\__init__.pyc", line 370, in onInstallCommand
  File "gui\installerGui.pyc", line 328, in showInstallGui
  File "gui\installerGui.pyc", line 182, in __init__
AttributeError: 'BoxSizerHelper' object has no attribute 'GetStaticBox'
INFO - core.main (11:08:15.675) - MainThread (19656):
Exiting
```

### Description of how this pull request fixes the issue:

Fix various crashing GUI bugs introduced to the installation process in #12181 

### Testing strategy:

Test installation process manually (with both a left-to-right and right-to-left system language)

- normal install
- portable install

System tests which test the ability to open and use the installation dialogs have been added for

- normal install
- portable install

### Known issues with pull request:

None

### Change log entry:

None, fixes new unreleased issue

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

File: source/gui/__init__.py [hunk 1]
```diff
@@ -804,7 +804,7 @@ class LauncherDialog(
 	helpId = "InstallingNVDA"
 
 	def __init__(self, parent):
-		super(LauncherDialog, self).__init__(parent, title=versionInfo.name)
+		super(LauncherDialog, self).__init__(parent, title=f"{versionInfo.name} {_('Launcher')}")
```
Comment (seanbudd) [inline source/gui/__init__.py:807]: possibly a controversial change? I added this to be more descriptive and so that we could test the "wait for speech" with something more unique

File: tests/system/robot/NVDAInstaller.robot [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+default startup
+	default exit if no installDir
+	start NVDAInstaller	standard-dontShowWelcomeDialog.ini
+
+default pass execution
+
+*** Test Cases ***
+
+Read install dialog
+	default exit if no installDir
```
Comment (feerrenrut) [inline tests/system/robot/NVDAInstaller.robot:36]: Because this is in the default startup I don't think it needs to be in the test?

File: tests/system/robot/NVDAInstaller.py [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+	# start install
+	spy.emulateKeyPress("alt+i")
+
+	spy.wait_for_specific_speech("To install NVDA to your hard drive, please press the Continue button.")
+
+	# exit NVDA Installer
+	spy.emulateKeyPress("escape")
+
+
+def read_portable_copy_dialog():
```
Comment (feerrenrut) [inline tests/system/robot/NVDAInstaller.py:49]: It would be good to have a docstring to explain the intent of this test. Eg:
"Smoke test the launcher dialogs used to create a portable copy of NVDA"

File: tests/system/robot/NVDAInstaller.py [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+import NvdaLib as _nvdaLib
+from NvdaLib import NvdaLib as _nvdaRobotLib
+_nvdaProcessAlias = _nvdaRobotLib.nvdaProcessAlias
+
+_builtIn: BuiltIn = BuiltIn()
+_process: _ProcessLib = _getLib("Process")
+_asserts: _AssertsLib = _getLib("AssertsLib")
+
+
+def read_install_dialog():
```
Comment (feerrenrut) [inline tests/system/robot/NVDAInstaller.py:30]: Also here, consider adding a docstring to explain the intent of the test:
"Smoke test the launcher dialogs used to install NVDA"

File: tests/system/libraries/NvdaLib.py [hunk 5]
```diff
@@ -196,6 +225,15 @@ def runKeyword(*args, **kwargs):
 			)
 		return remoteLib
 
+	def start_NVDAInstaller(self, settingsFileName):
+		builtIn.log(f"Starting NVDA with config: {settingsFileName}")
+		self.setup_nvda_profile(settingsFileName)
+		nvdaProcessHandle = self._startNVDAInstallerProcess()
+		process.process_should_be_running(nvdaProcessHandle)
+		self._connectToRemoteServer(connectionTimeoutSecs=30)
```
Comment (feerrenrut) [inline tests/system/libraries/NvdaLib.py:233]: This extra timeout is probably due to the start up splash sound. It might be worth a comment here to highlight that it is different from the usual NVDA startup timeout.

**Review by feerrenrut — CHANGES_REQUESTED** [review]

File: tests/system/robot/NVDAInstaller.robot (hunk 2 above)
Comment (seanbudd) [reply tests/system/robot/NVDAInstaller.robot:36]: weirdly, `Pass Execution If` skips the rest of the current setup, teardown and test, meaning it has to be done in each. Spent a while trying to find a simpler fix after noticing the behaviour. 

https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Pass%20Execution%20If

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: Does this mean that it skips the rest of the setup / startup step, but then tries to continue with the test?

If so, [the docs for pass execution](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Pass%20Execution) seem to suggest that tags can be added. Perhaps, the `Pass Execution If` could add or remove tags that prevent the tests that depend on `installDir` from running?

Comment (seanbudd) [reply tests/system/robot/NVDAInstaller.robot:36]: >Does this mean that it skips the rest of the setup / startup step, but then tries to continue with the test?

Correct

> Perhaps, the `Pass Execution If `could add or remove tags that prevent the tests that depend on installDir from running?

I tested this with the following code, by adding the `excluded_from_build` tag and removing the `installer` tag. The changes were logged properly but the tests were triggered (hence the changes logged). I think the choice of tests are done at the start of the robot test process. 

```
*** Keywords ***
default teardown
	${screenshotName}=	create_preserved_test_output_filename	failedTest.png
	Run Keyword If Test Failed	Take Screenshot	${screenShotName}
	quit NVDAInstaller

default startup
	Pass Execution If	not r'${installDir}'	"skipping due to not running on installer"	excluded_from_build	-installer
	start NVDAInstaller	standard-dontShowWelcomeDialog.ini

default pass execution

*** Test Cases ***

Read install dialog
	Log To Console	"@{TEST TAGS}"
	[Documentation]	Ensure that the install dialog can be read in full
	read_install_dialog	# run test

Read install dialog portable copy
	Log To Console	"@{TEST TAGS}"
	[Documentation]	Ensure that the portable copy install dialog can be read in full
	read_portable_copy_dialog	# run test

```

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: Yes, it looks like it isn't possible to change the tests dynamically: https://stackoverflow.com/questions/26369374/how-to-skip-a-specific-testcase-in-robot-framework

You might be able to configure this such that the installer tests are not in the set of tests that are run by default. Eg. a tag must be supplied by the robot invocation in order to make it run.

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: Then it would be an error for the suit if the `installDir` argument is not supplied. The suite startup is only run once, and is different from the test startup, which you have in the previous example. For an example of how to configure it see https://stackoverflow.com/questions/45204684/robot-framework-differences-between-suite-setup-and-test-setup. From there you could use `fail` rather than `pass execution if`

Comment (seanbudd) [reply tests/system/robot/NVDAInstaller.robot:36]: I from what I could tell, there was no way to override a variable that had already been passed in `eg --excluded exclude_from_build --include installer` doesn't work, so AppVeyor wouln't be able to use runsystemtests.bat. 

Maybe this is worth doing though and just putting the manual command in AppVeyor without a new batch file and robotArgs file

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: I suspect that if the tags to include are specified when robot is first run, it will only run tests matching that tag. In that case we can make the "default set of tests" only the tests with the "NVDA" tag. The installer tests wouldn't have this tag, instead they would have an `installer` tag. Then in the `robotArgs.robot` file (which has all the default options for running Robot framework), add a line to include tests with the `NVDA` tag.

Then when running from appveyor, we also include the `installer` tag.

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: I may have misunderstood you. Do you mean that when running robot from the command line, if an option is specified in the `robotArgs.robot` file, the same argument can't be specified as a command line argument as well?

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: It looks like it should be possible to at least override the --include argument see
From: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-argument-files

> When an argument file is used with other arguments, its contents are placed into the original list of arguments to the same place where the argument file option was. This means that options in argument files can override options before it, and its options can be overridden by options after it. It is possible to use --argumentfile option multiple times or even recursively

I've just tested this locally and it seems to work. Using `--dryrun` makes it faster to see which tests will run.

Comment (feerrenrut) [reply tests/system/robot/NVDAInstaller.robot:36]: To be clear, specifying `--include` on the command line in addition to in the `rogotArgs.robot` file resulted in additive behavior. Tests with both tags were included.

Comment (seanbudd) [reply tests/system/robot/NVDAInstaller.robot]: Thanks for looking into this, I figured there would be an easy option but as you would have noticed, the robot framework is somewhat unintuitive.

**Comment by amirsol81** [comment]
Any chance of implementing this so that we can resume testing NVDA alphas? Installation still gets aborted even with the latest alpha.

**Comment by XLTechie** [comment]
While it makes install testing an impossibility, can you not just install an 
earlier alpha, and then update it in-place?

**Comment by amirsol81** [comment]
@XLTechie You are right. Updating works whereas installing afresh doesn't. So I updated to Alpha 22057 successfully via NVDA's Check for Update facility.

File: tests/system/robot/NVDAInstaller.robot [hunk 6]
```diff
@@ -15,29 +15,23 @@ Test Setup	default startup
 Test Teardown	default teardown
 
 *** Keywords ***
-default exit if no installDir
-	Pass Execution If	not r'${installDir}'	"skipping due to not running on installer"
```
Comment (feerrenrut) [inline tests/system/robot/NVDAInstaller.robot]: I'd suggest a suite setup (not test setup) step that fails if this is missing. Failing should fail all the tests.

**Comment by seanbudd** [comment]
> Any chance of implementing this so that we can resume testing NVDA alphas? Installation still gets aborted even with the latest alpha.

Running the exe with the `--silent-install` flag should also work with current alphas, even though it crashes on exit

**Review by feerrenrut — APPROVED** [review]
Looks good @seanbudd 🎉
