### ISSUE TITLE
NVDA randomly crashing / freezing. 

### ISSUE THREAD

**Issue by aaaaaronx** [nvaccess/nvda#13707]
### Steps to reproduce:
This issue occurs randomly throughout the day, so it's hard to say how to reproduce it.
### Actual behavior:
As the user is working, nvda stops responding. Sometimes it's a few seconds of delay, sometimes he has to restart his machine to get nvda to respond again. Restarting seems to help but he is dealing with this issue at least daily. 

Per his ticket to me today: 
NVDA hung again while editing a Notepad++ file. Hung for only a few seconds. I then checked Chrome, and it was working. I turned off NVDA and am using Jaws right now without any problem. I attach the NVDA log file. Hope there is something there near the end.

Per his ticket to me yesterday:
"What happened was the NVDA was slowing down, and when I cut something out to paste elsewhere in a txt file in Notepad++, it crashed. I pressed the hot key to turn off NVDA but I never heard the little tune that plays when it turns off. I tried to turn on Jaws but it did not come on. A few minutes later I could get it to work (not sure which screen reader it was, since the voice is different in this panel) I went to the panel with the Power  button, task manager, wifi… This often (not always) talks when other things are not. I told it to restart, and it did, though it took a while."

Logfile is attached.

### Expected behavior:
no slowdowns or app freezes.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
[nvda.log](https://github.com/nvaccess/nvda/files/8720849/nvda.log)

Win10 x64 10.0.19044 
#### Name and version of other software in use when reproducing the issue:
Issue has been reported while using Chrome, notepad++, Outlook. 
#### Does the issue still occur after restarting your computer?
Not immediately. 
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Not sure
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I have not tried this yet but I'll look into it next.

**Comment by josephsl** [comment]
Hi, can you ask the client to try NVDA 2021.3.5 and 2022.1 RC 1 and see if that makes any difference? This is because 2020.4 is out of date at this point. Tanks,

**Comment by seanbudd** [comment]
Closing this as this likely an issue with an outdated and unsupported version of NVDA. 
If this can be reproduced with 2022.1 please let us know so we can investigate.

**Comment by aaaaaronx** [comment]
Hello again,

Sorry that I'm just following up, but the user reported the issue is still occurring after upgrading to 2022.1. 

I was able to grab this log file from somewhere in C:\, not sure if it's at all helpful.
[nvda.log](https://github.com/nvaccess/nvda/files/8922112/nvda.log)

**Comment by seanbudd** [comment]
Can you upload a log with more context? The current trimmed log is not helpful for debugging. If there are privacy concerns, please email to info@nvaccess.org

**Comment by aaaaaronx** [comment]
Here's what the user sent me today.
[errorLog.txt](https://github.com/nvaccess/nvda/files/8931246/errorLog.txt)

**Comment by seanbudd** [comment]
Note that the errors in both of these logs are different. In the second log, there appears to be issues when using IA2 interfaces.
There are many related errors in `errorLog.txt`. https://github.com/nvaccess/nvda/issues/13707#issuecomment-1159217761

```py
DEBUGWARNING - RPC process 9884 (SearchApp.exe) (07:57:08.114) - Dummy-3 (3928):
Thread 10368, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 154:
Not installing IA2 support as  process is suspendable
```

```py
DEBUGWARNING - NVDAObjects.behaviors._delayedDetection (09:43:31.252) - MainThread (5296):
Error fetching formatting for last character of previous word
Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 202, in _delayedDetection
  File "NVDAObjects\UIA\__init__.pyc", line 849, in getTextWithFields
AttributeError: 'NoneType' object has no attribute 'UIAElement'
```

```py
DEBUGWARNING - watchdog._watcher (07:57:07.055) - watchdog (9236):
Trying to recover from freeze. Listing stacks for Python threads:
...
  File "IAccessibleHandler\__init__.pyc", line 978, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 645, in processFocusWinEvent
  File "IAccessibleHandler\__init__.pyc", line 480, in winEventToNVDAEvent
  File "UIAHandler\__init__.pyc", line 838, in isUIAWindow
  File "UIAHandler\__init__.pyc", line 787, in _isUIAWindowHelper

...

set python locale to English_United States.1252
ERROR - RPC process 4212 (nvda_slave.exe) (09:44:08.180) - Dummy-12 (1168):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 118, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1239, in GetActiveObject
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147221021] Operation unavailable
```

**Comment by seanbudd** [comment]
For `errorLog.txt` is the lag only when using Internet Explorer?

**Comment by seanbudd** [comment]
Hi @aaaaaronx 

As the first 2 issues raised are unrelated and unable to be worked on, I have re-written the issue using your latest log.
Can you re-fill out the template with information related to `errorLog.txt`?

From the user, can you get a log where the issue is reproduced with advanced logging enabled.
- In Advanced Preferences, enable MSAA debug logging.
- From General Preference,  set log level to debug.
