### ISSUE TITLE
Installation process crashes due to StaticBoxSizer changes

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#12198]
The standard installation process crashes with the following traceback, likely caused by #12181

```
ERROR - unhandled exception (11:07:36.839) - MainThread (19656):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 831, in <lambda>
  File "gui\__init__.pyc", line 861, in onAction
  File "gui\__init__.pyc", line 370, in onInstallCommand
  File "gui\installerGui.pyc", line 328, in showInstallGui
  File "gui\installerGui.pyc", line 182, in __init__
AttributeError: 'BoxSizerHelper' object has no attribute 'GetStaticBox'
INFO - core.main (11:08:15.675) - MainThread (19656):
Exiting
```

_Originally posted by @OzancanKaratas in https://github.com/nvaccess/nvda/issues/12183#issuecomment-802345151_

**Comment by seanbudd** [comment]
Closing as duplicate of #12196

**Comment by zstanecic** [comment]
I can confirm the same with polish windows 10 locale

ERROR - unhandled exception (08:03:28.117) - MainThread (6604):

Traceback (most recent call last):

  File "gui\__init__.pyc", line 371, in onInstallCommand

  File "gui\installerGui.pyc", line 328, in showInstallGui

  File "gui\installerGui.pyc", line 182, in __init__

AttributeError: 'BoxSizerHelper' object has no attribute 'GetStaticBox'

 

From: Sean Budd ***@***.***> 
Sent: Friday, March 19, 2021 1:18 AM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Installation process crashes due to StaticBoxSizer changes (#12198)

 

The standard installation process crashes with the following traceback, likely caused by #12181 <https://github.com/nvaccess/nvda/pull/12181> 

ERROR - unhandled exception (11:07:36.839) - MainThread (19656):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 831, in <lambda>
  File "gui\__init__.pyc", line 861, in onAction
  File "gui\__init__.pyc", line 370, in onInstallCommand
  File "gui\installerGui.pyc", line 328, in showInstallGui
  File "gui\installerGui.pyc", line 182, in __init__
AttributeError: 'BoxSizerHelper' object has no attribute 'GetStaticBox'
INFO - core.main (11:08:15.675) - MainThread (19656):
Exiting

Originally posted by @OzancanKaratas <https://github.com/OzancanKaratas>  in #12183 (comment) <https://github.com/nvaccess/nvda/pull/12183#issuecomment-802345151>
