### ISSUE TITLE
At least with Braille, object navigation throws errors in XAML apps, like WhatsApp

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/nvda#18399]
### Steps to reproduce:
1. Open WhatsApp desktop
2. Use laptop:nvda+shift+left arrow to object nav backwards several times.

### Actual behavior:
Ad some point, e.g. for objects like `Chats`, `End to end encrypted`, the following is logged:

```log
ERROR - eventHandler.executeEvent (10:49:13.254) - MainThread (4452):
error executing event: becomeNavigatorObject on <NVDAObjects.Dynamic_XamlEditableTextEditableTextWithAutoSelectDetectionUIA object at 0x0AB429B0> with extra args of {'isFocus': False}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1398, in event_becomeNavigatorObject
  File "braille.pyc", line 3119, in handleReviewMove
  File "braille.pyc", line 2961, in _doNewObject
  File "braille.pyc", line 2261, in getFocusRegions
  File "braille.pyc", line 1551, in update
  File "NVDAObjects\UIA\__init__.pyc", line 1114, in compareEndPoints
AttributeError: 'NVDAObjectTextInfo' object has no attribute '_rangeObj'
```

### Expected behavior:
No errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-37061

#### Windows version:
24H2

#### Name and version of other software in use when reproducing the issue:
WhatsApp 2.2524.4.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by LeonarddeR** [comment]
Possibly caused by #18271, though I don't see how.

**Comment by nvdaes** [comment]
I can reproduce this with NVDA 2025.2beta1, on Windows 11 24H2 (10.0.26100.4349), and 5319275A.WhatsAppDesktop 2.2524.4.0 (info obtained with the sayProductNameAndVersion add-on from the store.

**Comment by LeonarddeR** [comment]
I could indeed pinpoint this to #18271.

I think the reason is as follows.

1. An object becomes navigator object. Note that the object in question has no navigable text but has a TextPattern and therefore UIATextInfo is assumed.
2. `New braille regions are fetched with `braille.getFocusRegions`
3. Braille assumes the TextInfo should be used because `braille.NVDAObjectHasUsefulText` returns True
4. In `braille.TextInfoRegion.update`, `self._readingInfo = readingInfo = self._getSelection()` results in NVDAObjectTextInfo. Later on, `start = readingInfo.obj.makeTextInfo(textInfos.POSITION_FIRST)` results in an UIATextInfo.

@jcsteh given you're the author of #18271, Would you like to think along? I actually think there are multiple problems here.

1. `braille.NVDAObjectHasUsefulText` may no longer return True when hasNavigableText is False and the object is yet an instance of EditableText. That said, ideally this would not be possible.
2. UIA objects `_get_TextInfo` property should not only rely on Text Pattern presence, but should perform extra checks, like the checks in `_hasNavigableText`, but not that particular property because that'd would cause recursion.

**Comment by jcsteh** [comment]
Hmm. I think we should probably just revert #18271 given that we're in beta now. and the path forward is unclear.

Why on earth do we have an EditableText that doesn't have navigable text? That is just silly. We have explicit code to add EditableText if the text pattern exists, but IMO that isn't a sufficient justification to treat it as EditableText. But I'd have to dig to figure out why that change was made and it's unclear if changing that would cause its own regressions.

**Comment by jcsteh** [comment]
Reverting #18271 would also require reverting #18318.

**Comment by jcsteh** [comment]
> We have explicit code to add EditableText if the text pattern exists, but IMO that isn't a sufficient justification to treat it as EditableText.

Apparently Mick did this over 16 years ago in 47a4efa790d67ba7f82210fc7ac8a0bf83a230e2, though it has been through several refactors since then; e.g. my 4b854686ea7c0a0ac178c75c536a62b1c221d995 over 15 years ago. I guess the thinking was that if something has the Text pattern, it *might* be editable, but IMO that's fairly questionable these days.

**Comment by LeonarddeR** [comment]
I'm working on a patch which I think is not that risky and should limit extra calls to a minimum.

**Comment by jcsteh** [comment]
Meh, I'll probably just submit a PR to revert #18271 and #18318 and then reopen all the associated issues. I'm concerned this web is going to be too hard to untangle.

**Comment by jcsteh** [comment]
@seanbudd, I assume I should just submit a revert PR against beta in this case because we need to get this out of beta, and then the merge from beta to master will propagate this to master as well? Or is there another path I should follow here?

**Comment by seanbudd** [comment]
Hey @jcsteh - that approach sounds correct to me

**Comment by seanbudd** [comment]
Make sure to use our [revert template](https://github.com/nvaccess/nvda/blob/master/.github/PULL_REQUEST_TEMPLATE/revert.md) to document the opened/closed issues
