### PR TITLE
Revert Applications Volume Adjuster

### LINKED ISSUE #17124: Application volume adjuster: make the setting profile independent
### Steps to reproduce:
1. Open NVDA
2. Create profiles for different applications with different audio playback (e.g. MS Teams, a browser of your choice, audio editing application etc.
3. Enable the application volume adjuster while on the standard NVDA profile
4. Play some audio on an applicationw ith a profile (e.g. a youtube video on Chrome)
5. Adjust the volume of all applications with the coresponding commands while focusing the desktop
6. Switch to the Chrome window playing the Youtube video with alt+tab
7. Enable the application volume adjuster on this application as well
8. Repeat step 5 while focusing desktop
9. Switch back to the Chrome window
10. Press nvda+alt+delete to mute the application
11. Switch back to desktop to activate the standard NVDA profile
12. press nvda+alt+delete (you will hear applications unmuted)
13. Switch back to the the Chrome window with the Audio playback from the Youtube video
14. Change the applications volume with nvda+alt+pg up and pg down

### Actual behavior:
* Steps 5 and 8: The volume of Chrome Audio playback from the Youtube video is not changed.
* Step 14: as soon as the change volume command is pressed, the Youtube audio playback is muted, although I unmuted all applications in step 12.

### Expected behavior:
The application volume adjuster should not be profile dependend in order to avoid these issues. Also it is confusing to describe the setting as "it adjusts the volume of all applications other than NVDA". In this case this is not true because it depends on whether you enabled the applications volume adjuster for all your profiles or not.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
last alpha

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
Any application with a NVDA profile

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
n/a

### LINKED ISSUE #17654: Exception in on_session_created when windows sound is played after replugging output device
### Steps to reproduce:
1. Set the external device as default output device in windows settings, and also in the NVDA settings. Probably external sound card is needed for this.
2. Set sound split mode to "NVDA in both channels and applications in both channels.
3. Unplug default output device.
4. Replug output device.
5. Perform an action that causes windows sounds to play, for example, open the NVDA log, go to the end, and press right and down arrows several times.

### Actual behavior:

NVDA error sound is played, and the following errors are logged:
```
ERROR - comtypes._comobject.call_without_this (17:39:25.579) - Dummy-11 (14888):
Exception in IAudioSessionNotification.OnSessionCreated implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "pycaw\callbacks.pyc", line 53, in OnSessionCreated
  File "audio\utils.pyc", line 87, in on_session_created
  File "pycaw\utils.pyc", line 87, in ProcessId
_ctypes.COMError: (-2004287484, None, (None, None, None, 0, None))
```
### Expected behavior:

No errors should occur.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-35103,8ec1116d (2025.1.0.35103)
#### Windows version:
Windows 11 23H2 (AMD64) build 22631.4751
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### LINKED ISSUE #17656: NVDA Alpha: NVDA does not control the volume of applications that uses an audio output device other than Windows default device.
### Actual behavior:

- Start a system with two audio output devices.
- Launch an application that uses the device that is not the default audio output device of Windows.
- Modify the potentiometer "Volume of Other Applications" or check the "Mute Other Apps" Mute "of the" Audio "category and validate.

The volume of the audio flow of the application does not change or the sound is not cut.
This is also valid for the separation of sound:
- Configure NVDA so that it uses the same audio output device as this application.
- Modify in the "audio" settings of NVDA the sound separation mode to separate the sound of NVDA and the application and validate.
### Expected behavior:

Let NVDA control the volume of applications using another audio output device other than the one defined by default by Windows,
- or it is clearly indicated in the NVDA user manual that only the Windows audio output device is affected by this functionality.
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
alpha-35103,8ec1116d x86

### Windows version:
Windows 10 22H2 (10.0.19045) workstation AMD64

#### Name and version of other software in use when reproducing the issue:
radioSure, But any audio application can do the trick
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no possible
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
no tested

### LINKED ISSUE #17882: NVDA does not announce when application volume control feature is toggled using assigned gesture
### Steps to reproduce:

- Go to NVDA menu, Preferences and Input gestures

- assign a gesture  to turn on or off  application volume control feature, for example: NVDA+alt+V (all layouts)

### Actual behavior:

try press NVDA+alt+V, NVDA does not announce that this feature has been turned on or off, when entering the gesture has been assigned, there is an error

### Expected behavior:

NVDA should notify the user when they turn on or off this feature, for example: Volume control of the application  enable or something

### NVDA logs, crash dumps and other attachments:
ERROR - scriptHandler.executeScript (12:59:52.872) - MainThread (4624):
error executing script: <bound method GlobalCommands.script_toggleApplicationsVolumeAdjuster of <globalCommands.GlobalCommands object at 0x066C87D0>> with gesture 'NVDA+alt+v'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "globalCommands.pyc", line 4908, in script_toggleApplicationsVolumeAdjuster
  File "audio\appsVolume.pyc", line 151, in _toggleAppsVolumeState
  File "audio\appsVolume.pyc", line 90, in _updateAppsVolumeImpl
AttributeError: 'AppsVolumeAdjusterFlag' object has no attribute 'calculated'

#### NVDA installed/portable/running from source:
Portable (Latest Alpha)
#### NVDA version:
35820,0fc7254e (2025.1.0.35820)
#### Windows version:
Windows 11 24H2 (AMD64) build 26100.3624
#### Does the issue still occur after restarting your computer?
Yes 
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, because the previous versions of NVDA  (2024.4.2) don't  have this feature
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

### PR DESCRIPTION
**Pull request by seanbudd**
### Reverts PR
Reverts #17271
Reverts #16591
Reverts #17634

### Issues fixed
Fixes #17654
Fixes #17882
Fixes #17124
Fixes #17656

### Issues reopened

Reopens #16052

### Reason for revert
- #17654: The applications volume adjust feature is affecting Windows sound output even if the feature is disabled.
- #17882: bug: NVDA does not announce when application volume control feature is toggled using assigned gesture
- #17124: unclear UX in regards to if the settings should be profile independent
- #17656: NVDA doesn't control the volume of applications which use non-default windows output

### Can this PR be reimplemented? If so, what is required for the next attempt

- Refer to debug suggestions in https://github.com/nvaccess/nvda/issues/17654#issuecomment-2649543993
- Ensure #17124 is considered in the next attempt
- See #17885 for fix for #17882
- #17656 should at least be documented, if not resolved

### CODE REVIEW

**Comment by seanbudd** [comment]
cc @CyrilleB79 @mltony @LeonarddeR @ABuffEr @codeofdusk: as those who contributed to this issue/feature discussion

**Comment by LeonarddeR** [comment]
While it is a pity that this is reverted for those who really like this feature, I think this is the right decision.

**Comment by seanbudd** [comment]
@LeonarddeR - we are not aware of any explicit known fixes for sound split from this PR, no associated logged issues were mentioned in the PR.

**Comment by seanbudd** [comment]
I'd also mention that it is fairly possible/likely the bug was introduced via the refactoring, not necessarily from the feature itself

**Comment by beqabeqa473** [comment]
i don't think soundsplit as well as application volume adjuster need to be in nvda core. They can greatly fit in addon.
NVDA is primarily a screenreader, and if user needs such functionality, they can easily install an addon.

I recall discussion when nvaccess was strongly against including systraylist addon into core, but i am sure that feature more likely is direct screenreader feature rather than these features, which simply overload application.
I think NVaccess philosophy should be as it was earlier, include in the core features, which are directly related to screenreader.

**Comment by HBM301** [comment]
Hello everyone, to be honest, I THINK the sound split feature may also be necessary in certain cases, such as checking the position of a headset or speaker,Regarding the application's volume control feature, I'm not entirely sure whether it is necessary, as some add-ons already provide this functionality

**Comment by SaschaCowley** [comment]
@LeonarddeR IIRC when I tried to track down the commit that introduced #17654 the earliest commit I could track it to was the refactor of sound split. It's also  not present in 2024.4.2.

**Review by SaschaCowley — APPROVED** [review]
