### ISSUE TITLE
Edit controls in explorer fail when they have a native UIA implementation

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15375]
Regression from #15314

### Steps to reproduce:
1. On a folder in Windows Explorer, open properties (alt+Enter)
2. Go to the security tab
3. Press the advanced button

### Actual behavior:
Read only edit boxes don't read. This is because they have an overlay in the explorer appModule that is bound to IAccessible rather than Edit.
```
error executing event: gainFocus on <NVDAObjects.Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAutoSelectDetectionUIAWindowNVDAObjectEditableIndentNav object at 0x07F71350> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 139, in setFocusObject
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 656, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1059, in _get_parent
AttributeError: 'Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAut' object has no attribute 'IAccessibleChildID'

```

### Expected behavior:
Edit boxes read correctly.

#### NVDA version:
2023.3 Beta branch

#### Windows version:
Windows 11 22H2

### Additional details
The code conflicting with UIA was introduced in 32a0f2298a, pr #8643. Cc @lukaszgo1 
Personally I'm tempted to remove this RTL and LTR workaround from the explorer appModule. While this will reintroduce these marks in the said edit boxes, removing the marks from the windowText is no viable solution to me as it will cause of by one errors when reporting the symbol or character under the caret.

**Comment by lukaszgo1** [comment]
thanks for poking me @leonardder. Indeed, making `ReadOnlyEditBox` inherit from `IAccessible` is a mistake (this was one of my first PR's). From a quick test making it inherit from `NVDAObjects.window.Window`, makes the error go away, and does not have any negative effects. While indeed removing the RTL and LTR marks may, theoretically, cause errors when moving with the caret, this is not noticeable in practice, since it affects only read only edit fields, which are not focusable. The only case in which it may cause errors in my testing, is when you manually navigate to one of the edit fields with object nav, route focus to it and start moving with arrow keys. It is also worth pointing out that the entire content of the field can be read - the only problem is the error sound played at the end of the field.
I cannot say how annoying for Braille users (that was the initial motivation behind #8361) is presence of these symbols.
My initial thought would be to prefer the smallest fix possible for 2023.3, i.e. change the base class to `NVDAObjects.window.Window`, and if you feel strongly about not removing these symbols handle that in a separate issue, as problems caused by this removal are not new.

**Comment by leonardder** [comment]
Thanks for your quick response.

I actually feel like we should reintroduce edit as bad UIA Class name globally. There is also some oddness going on with the edit control when renaming files in explorer. The window text is set as the name of the control. This is really not what should happen.

**Comment by lukaszgo1** [comment]
> I actually feel like we should reintroduce edit as bad UIA Class name globally. There is also some oddness going on with the edit control when renaming files in explorer. The window text is set as the name of the control. This is really not what should happen.

This is not reproducible for me on Windows 10. In fact when renaming a file the edit control uses IAccessible.
