### ISSUE TITLE
Revert configuration gives error

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13679]
### Steps to reproduce:
**When you select 'No Braille' in the Braille device selection combo box and click the OK button, you will not be able to reproduce this.**

1. Launch NVDA2022.1Beta4;
2. Feel free to change a config, such as checking or unchecking an option in the Document Formatting panel, and then click the OK button;
3. Press Ctrl +NVDA+R to try to reverse this config.

### Actual behavior:
NVDA throws something errors and play an error sound.
I found by observing the logs that this should be a regression introduced by #13191.
Here are the key log snippets:
```
Loaded braille display driver seikantk, current display has 0 cells.
ERROR - queueHandler.flushQueue (21:34:56.030) - MainThread (9512):
Error in func resetConfiguration
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "core.pyc", line 212, in resetConfiguration
  File "braille.pyc", line 2341, in terminate
  File "braille.pyc", line 1743, in terminate
  File "brailleDisplayDrivers\seikantk.pyc", line 191, in terminate
AttributeError: 'BrailleDisplayDriver' object has no attribute '_dev'
ERROR - eventHandler.executeEvent (21:34:57.220) - MainThread (9512):
error executing event: valueChange on <NVDAObjects.IAccessible.IAccessible object at 0x0E106090> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 285, in executeEvent
  File "eventHandler.pyc", line 99, in __init__
  File "eventHandler.pyc", line 108, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1615, in event_valueChange
  File "NVDAObjects\__init__.pyc", line 1189, in event_valueChange
AttributeError: 'NoneType' object has no attribute 'handleUpdate'
```

### Expected behavior:
No Errors.

#### NVDA installed/portable/running from source:
installed and portable
#### NVDA version:
2022.1Beta4
#### Windows version:
Windows 10 21H2 (x64) build 19044.1682
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.3.5 cannot reproduce this.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment]
Cc @feerrenrut, @seanbudd

**Comment by seanbudd** [comment]
Hi @cary-rowen - I cannot reproduce this. Do you need to have a braille device connected for this to be an issue? These problems are very config specific. Could you please upload a full log or a copy of your config? Thanks

**Comment by seanbudd** [comment]
Also - is there any affected behaviour? Can you successfully reset and revert your configuration?

**Comment by cary-rowen** [comment]
@seanbudd 

Hello, if the Seika device has never been connected using the 'automatic', this issue may not occur.

Otherwise, you can reproduce the situation regardless of whether the device is currently connected, as long as you have ever connected a Seika device via bluetooth and set the Braille device to "Automatic".

Below is full log(From the log, although I did not turn on the Seika device NVDA still tried to connect through the previous connection record):
[log.txt](https://github.com/nvaccess/nvda/files/8666978/log.txt)

**Comment by cary-rowen** [comment]
I made a simple test: I changed https://github.com/nvaccess/nvda/blob/f90caa927f9eeb0af21c816fc280e4d1bff6ed1d/source/brailleDisplayDrivers/seikantk.py#L191 to ```if hasattr(self, '_dev'): self._dev.close()``` can solve this

**Comment by seanbudd** [comment]
> Also - is there any affected behaviour? Can you successfully reset and revert your configuration?

@cary-rowen  any answers for these questions

**Comment by cary-rowen** [comment]
Hi @seanbudd 

> Also - is there any affected behaviour? Can you successfully reset and revert your configuration?

Sorry I ignored this comment.

No, I cannot successfully restore my configuration when the error occurs.

**Comment by seanbudd** [comment]
This issue will be fixed in 2022.2 instead of 2022.1:

This is because:
* it is late in the release period, rc1 is due today
* this only affects Seika Notetaker bluetooth users.
* there is a workaround - selecting the Seika Notetaker driver explicitly, instead of "automatic"

**Comment by cary-rowen** [comment]
Hi, @seanbudd 

Even so, I still think it's serious enough,
1. 'automatic' is the default option for NVDA.
2. general users may not know how this error is caused, so the possibility of solving this problem by explicitly specifying "Seika Notetaker" is almost nonexistent.

Thanks

**Comment by cary-rowen** [comment]
Hi, @seanbudd 
Based on my comment above, What do you think?

**Comment by seanbudd** [comment]
@cary-rowen the reasons outlined above still stand, we cannot indefinitely delay a release that contains many more fixes of a similar or higher priority.

**Comment by seanbudd** [comment]
@cary-rowen - can you confirm this is fixed on the latest alpha?

**Comment by cary-rowen** [comment]
Hi @seanbudd  
I tested the latest alpha version and the issue has been fixed, thanks for your effort, you can close this.
Thanks
