### PR TITLE
Fix profile upgrade from 13 to 14

### LINKED ISSUE #17587: Config upgrade steps (13 to 14): NameError (name ")") is not defined
Hi,
This looks like a config migration issue:

### Steps to reproduce:
Prerequisite: alpha builds earlier than alpha-34909,0f7e961a:

1. Install an earlier alpha build.
2. Try upgrading to alpha-34909,0f7e961a (when prompted, select "update now").

### Actual behavior:
An error occurs while upgrading config spec from 13 to 14 (speech/outputDevice -> audio/outputDevice), resuling in NVDA reporting config corruption.

### Expected behavior:
No issues.

### NVDA logs, crash dumps and other attachments:
ERROR - config.ConfigManager._initBaseConf (16:28:20.773) - MainThread (6604):
Error loading base configuration; the base configuration file will be reinitialized. A copy of your previous configuration file will be saved at C:\Users\User\AppData\Roaming\nvda\nvda.ini.corrupted.bak
Traceback (most recent call last):
  File "config\__init__.pyc", line 582, in _initBaseConf
  File "config\__init__.pyc", line 633, in _loadConfig
  File "config\__init__.pyc", line 629, in _loadConfig
  File "config\profileUpgrader.pyc", line 26, in upgrade
  File "config\profileUpgrader.pyc", line 42, in _doConfigUpgrade
  File "config\profileUpgradeSteps.pyc", line 428, in upgradeConfigFrom_13_to_14
  File "config\profileUpgradeSteps.pyc", line 461, in _friendlyNameToEndpointId
  File "nvwave.pyc", line 39, in <module>
  File "NVDAHelper.pyc", line 32, in <module>
  File "eventHandler.pyc", line 13, in <module>
  File "api.pyc", line 14, in <module>
  File "textInfos\__init__.pyc", line 29, in <module>
  File "controlTypes\__init__.pyc", line 6, in <module>
  File "controlTypes\formatFields.pyc", line 34, in <module>
NameError: name '_' is not defined

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-34909,0f7e961a

#### Windows version:
Windows 11 24H2 (build 26100.2605)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
A portable copy of the previous alpha build with user settings was saved as a backup

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No issues in earlier alphas such as alpha-34883,4bab7223

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not applicable

### Additional testing performed:

* Updating a portable copy of NVDA running an earlier alpha build to alpha-34909: fails
* Updating NVDA 2024.4.1 RC portable version to alpha-34909: fails

The above traceback is accompanied by an attribute error (next issue).

Thanks.

### LINKED ISSUE #17588: NVDA alpha-34909: attribute error (module "NVDAHelper" has no attribute "localLib")
Hi,
Continuing from #17587:

### Steps to reproduce:
Prerequisite: use an earlier alpha build such as alpha-34883,4bab7223:

1. Download alpha-34909,0f7e961a.
2. Attempt to update to the new alpha build.

### Actual behavior:
The update process stops with an attribute error (traceback below).

### Expected behavior:
The update process works as normal.

### NVDA logs, crash dumps and other attachments:
CRITICAL - __main__ (16:28:23.547) - MainThread (6604):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 314, in <module>
  File "core.pyc", line 1012, in main
  File "watchdog.pyc", line 314, in initialize
AttributeError: module 'NVDAHelper' has no attribute 'localLib'

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-34909,0f7e961a

#### Windows version:
Windows 11 24H2 (build 26100.2605)

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
A portable copy of alpha-34883,4bab7223 with user settings is saved as a backup.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No issues with alpha-34883,4bab7223

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### Additional context:
The traceback from this issue and #17587 appear together and happens when upgrading from an earlier alpha to alpha-34909,0f7e961a. The workarond is to create a clean copy of alpha-34909,0f7e961a as a portavle version and override other NVDA versions (portable or installed).

Thanks.

### PR DESCRIPTION
**Pull request by SaschaCowley**
### Link to issue number:

Fixes #17587
Fixes #17588

### Summary of the issue:

The profile upgrade steps introduced in #17547 would cause NVDA to crash, and the user's configuration to be reset, if the user had an audio output device set in their NVDA configuration.

### Description of user facing changes

Upgrading from configuration version 13 to 14 no longer crashes NVDA and resets the user's configuration.

### Description of development approach

The issue was caused because `config.profileUpgradeSteps.upgradeConfigFrom_13_to_14` attempts to import `nvwave`, which, through its own imports, eventually attempts to use gettext. Since gettext has not yet been initialised, this raises an exception. As we are so early in NVDA initialisation, this exception causes the rest of NVDA's initialisation to fail critically.

To resolve this, `_getOutputDevices` and `_AudioOutputDevice` have been moved to the new `utils.mmdevice`. I initially thought to move them to `audio.utils`, but initialisation of `audio` runs into the same problem.

### Testing strategy:

Checked out `a7fa0d6`, made sure the config version was `13`, ran NVDA and selected an audio output device. Checked out `fixProfileUpgrade`, ran NVDA, and ensured that it ran as expected, the profile was correctly updated, there was no loss of settings, and the correct output device was in use.

### Known issues with pull request:

None known.

### Code Review Checklist:

- [x] Documentation:
  - Change log entry
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] UX of all users considered:
  - Speech
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] API is compatible with existing add-ons.
- [x] Security precautions taken.

@coderabbitai summary

### CODE REVIEW

File: tests/unit/test_config.py [hunk 1]
```diff
@@ -1026,7 +1026,9 @@ def test_outputDeviceFound(self):
 			outputDevice=Friendly name
 		"""
 		profile = _loadProfile(configString)
+		print(profile)
 		upgradeConfigFrom_13_to_14(profile)
+		print(profile)
```
Comment (seanbudd) [inline tests/unit/test_config.py:1031]:
```suggestion
		upgradeConfigFrom_13_to_14(profile)
```

File: source/utils/mmdevice.py [hunk 2]
```diff
@@ -0,0 +1,48 @@
+# A part of NonVisual Desktop Access (NVDA)
+# Copyright (C) 2025 NV Access Limited
+# This file is covered by the GNU General Public License.
+# See the file COPYING for more details.
+from collections.abc import Generator
```
Comment (seanbudd) [inline source/utils/mmdevice.py:5]:
```suggestion

from collections.abc import Generator
```

**Review by seanbudd — APPROVED** [review]
