### ISSUE TITLE
NVDA Alpha 22012: installation aborts unexpectedly

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#12196]
With NVDA Alpha 22012, attempting to move past the License agreement in the Installation dialog by ticking the I Agree check box and selecting the Install NVDA on this computer button results in the unexpected closure of the installation wizard.
### Steps to reproduce:
1. Run NVDA Alpha 22012 installer.
2. Tick the I agree check box.
3. Select the Install on this computer button.
### Actual behavior:
The installation wizard aborts and NVDA keeps using the temporary copy it has generated until it's closed and restarted.
### Expected behavior:
The next Installation wizard window should come up to allow installation to continue.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Currently running NVDA Alpha 21882, and trying to install NVDA Alpha 22012
#### Windows version:
Win 10 Pro 64-Bit, Version 20H2 (OS Build 19042.867)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Alpha 21895 can be installed successfully, but I haven't tried alphas between 21895 and 22012.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by seanbudd** [comment]
The standard installation process crashes with the following traceback, likely caused by #12181, looking at this on #12199

```
ERROR - unhandled exception (11:07:36.839) - MainThread (19656):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 831, in <lambda>
  File "gui\__init__.pyc", line 861, in onAction
  File "gui\__init__.pyc", line 370, in onInstallCommand
  File "gui\installerGui.pyc", line 328, in showInstallGui
  File "gui\installerGui.pyc", line 182, in __init__
AttributeError: 'BoxSizerHelper' object has no attribute 'GetStaticBox'
INFO - core.main (11:08:15.675) - MainThread (19656):
Exiting
```

**Comment by amirsol81** [comment]
@seanbudd Any progress regarding this?
