### PR TITLE
Add landmark property to the base NVDAObject

### LINKED ISSUE #7490: can't get landmark from a pdf in edge
### Steps to reproduce:

1. Open this pdf in edge.
2. Read down by line, and move forward by character after my objective and proficiency.
3. Note this error.
error executing script: <bound method EdgeHTMLTreeInterceptor.script_moveByCharacter_forward of <NVDAObjects.UIA.edge.EdgeHTMLTreeInterceptor object at 0x051FCF90>> with gesture u'right arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 196, in script_moveByCharacter_forward
  File "cursorManager.pyc", line 141, in _caretMovementScriptHelper
  File "speech.pyc", line 749, in speakTextInfo
  File "treeInterceptorHandler.pyc", line 217, in getTextWithFields
  File "NVDAObjects\UIA\edge.pyc", line 179, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 588, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 502, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\edge.pyc", line 137, in _getControlFieldForObject
AttributeError: 'UIA' object has no attribute 'landmark'

### Expected behavior:
The info on those lines should read.

### Actual behavior:
An error.

### System configuration:
Version: next-14293,8d368f7e

NVDA Installed or portable: Installed

Other information:
@leonardder might this be a regression from your localized landmarks fix? Thought'd check.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #7490

### Summary of the issue:
Regression from #7328, sometimes an error is raised while navigating through a document in Edge, for example a PDF document.

### Description of how this pull request fixes the issue:
Adds the landmark property added in #7328 to the base NVDAObject, so getting the landmark property from an object always returns something.

### Testing performed:
@derekriemer: Could you please double check whether this fixes the PDF issue you reported?

### Known issues with pull request:
None I'm aware of

### Change log entry:
None, regression from 2017.2.

@MichaelDCurran, since this is a regression from 2017.2, I think this is best merged into master after @DerekRiemer confirms that it fixes the issue.

### CODE REVIEW

**Comment by derekriemer** [comment]
this fixes the issue.

**Review by michaelDCurran — APPROVED** [review]
