### PR TITLE
move/remove imports to prevent circular dependencies

### LINKED ISSUE #12399: NVDA crashes when uninstalling add-ons importing `gui` at the module level in installTasks.
### Steps to reproduce:

1. Install an add-on which imports `gui` in installTasks at the module level, such as [Report passwords](https://github.com/nvdaes/reportPasswords/releases/download/1.0/reportPasswords-1.0.nvda-addon)
2. Try to reinstall it.
### Actual behavior:
NVDA fails to restart properly and the following is in the log:
```

CRITICAL - __main__ (14:54:55.813) - MainThread (8104):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 266, in <module>
    core.main()
  File "core.py", line 351, in main
    import speech
  File "speech\__init__.py", line 7, in <module>
    from .speech import (
  File "speech\speech.py", line 16, in <module>
    import api
  File "api.py", line 12, in <module>
    import review
  File "review.py", line 10, in <module>
    from NVDAObjects import NVDAObject, NVDAObjectTextInfo
  File "NVDAObjects\__init__.py", line 18, in <module>
    import eventHandler
  File "eventHandler.py", line 16, in <module>
    import treeInterceptorHandler
  File "treeInterceptorHandler.py", line 11, in <module>
    import documentBase
  File "documentBase.py", line 7, in <module>
    from scriptHandler import isScriptWaiting
  File "scriptHandler.py", line 13, in <module>
    from speech import sayAll
  File "speech\sayAll.py", line 11, in <module>
    from .speech import (
ImportError: cannot import name 'speak' from 'speech.speech' (D:\my_repos\nvda\source\speech\speech.py)
```

### Expected behavior:
NVDA should restart properly.

#### NVDA installed/portable/running from source:
From sources

#### NVDA version:
Latest master as of May 11-th

#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - this has been introduced by #12251 and reverting this PR fixes the problem.

#### If add-ons are disabled, is your problem still occurring?
No but this issue is about NVDA's interaction with add-ons.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

## Possible solutions:

I've investigated the problem and see three possible ways in which this can be fixed: 
1. By refactoring `gui` so that most of the code which is currently in `gui\__init__.py` is moved to smaller files. This  is unlikely to be done before 2021.1 and given that it should be preferably done in stages I'll create a new issue to discuss the best way to go about this.
2. By converting `speech\sayAll` to a package so that main file contains only function needed to initialize it and the rest including imports from speech are moved to a separate files.
3. The smallest fix in terms of code would be to import `speech` lazily in the `ui` module and move `gui.IndeterminateProgressDialog` to a separate file in the gui which  would make sure that `speech` is not imported there at the module level.

cc @seanbudd I'm happy to work on this assuming you're happy with one of my proposals above / can suggest a better alternative.

### PR DESCRIPTION
**Pull request by seanbudd**
### Link to issue number:

Fixes #12399 

### Summary of the issue:

NVDA fails to uninstall addons which import `gui` due to a circular dependency going from speech.py -> sayAll.py

While the refactor of speech/sayAll #12251 was designed to make fixing this problem simpler, it did not actually fix this issue. 

### Description of how this pull request fixes the issue:

- makes sayAll no longer dependent on speech by injecting the dependencies on initialization 
- removes unused imports
- moves imports to lazy load

### Testing strategy:

Manual testing that #12399 is fixed

### Known issues with pull request:

none

### Change log entries:

None needed

### Code Review Checklist:

- [x] Pull Request description is up to date.
- [x] Unit tests.
- [x] System (end to end) tests.
- [x] Manual tests.
- [x] User Documentation.
- [x] Change log entry.
- [x] Context sensitive help for GUI changes.

### CODE REVIEW

File: source/documentBase.py [hunk 1]
```diff
@@ -4,7 +4,6 @@
 #See the file COPYING for more details.
 
 from baseObject import AutoPropertyObject, ScriptableObject
-from scriptHandler import isScriptWaiting
 import config
 import textInfos
 import speech
```
Comment (feerrenrut) [inline source/documentBase.py:9]: I think you can do the same with `speech`

File: source/core.py [hunk 2]
```diff
@@ -353,7 +353,12 @@ def main():
 	speech.initialize()
 	from speech import sayAll
 	log.debug("Initializing sayAllHandler")
-	sayAll.initialize()
+	sayAll.initialize(
+		speech.speak,
+		speech.speakObject,
+		speech.getTextInfoSpeech,
+		speech.SpeakTextInfoState,
+	)
```
Comment (feerrenrut) [inline source/core.py:361]: Do you think this could happen from within `speech.initialize`?

Is there any chance something could depend on sayAll, and somehow initalize the speech package, neglecting to initialize the sayAll module. It would be easy to miss that requirement. It would only be a problem if core doesn't run. Which seems to be the case in addon uninstall..... right? Though, I don't see any reason an addon would need to use sayAll during uninstall.

**Review by feerrenrut — CHANGES_REQUESTED** [review]

File: source/documentBase.py (hunk 1 above)
Comment (seanbudd) [reply source/documentBase.py]: I also moved `ui`

File: source/core.py (hunk 2 above)
Comment (seanbudd) [reply source/core.py]: I agree that it makes more sense there. It also makes the dependency more obvious.

File: source/speech/__init__.py [hunk 3]
```diff
@@ -142,13 +144,22 @@
 import synthDriverHandler
 import config
 from .speech import initialize as speechInitialize
+from .sayAll import initialize as sayAllInitialize
 
 
 def initialize():
-	"""Loads and sets the synth driver configured in nvda.ini."""
+	""" Loads and sets the synth driver configured in nvda.ini.
+		Initializes the state of speech and initializes the sayAllHandler
```
Comment (seanbudd) [inline source/speech/__init__.py:152]:
```suggestion
	Initializes the state of speech and initializes the sayAllHandler
```

File: source/documentBase.py [hunk 4]
```diff
@@ -140,10 +139,11 @@ def _getNearestTableCell(self, tableID, startPos, origRow, origCol, origRowSpan,
 		raise LookupError
 
 	def _tableMovementScriptHelper(self, movement="next", axis=None):
-		# documentBase shouldn't depend on scriptHandler
-		# documentBase is a core module and should not depend on UI classes
-		# this function should be somewhere else or dependency injected
+		# documentBase is a core module and should not depend on these UI modules. (#12404)
```
Comment (feerrenrut) [inline source/documentBase.py:142]: Can you add, "and so they are imported at run-time"

File: source/speech/__init__.py [hunk 5]
```diff
@@ -144,13 +144,22 @@
 import synthDriverHandler
 import config
 from .speech import initialize as speechInitialize
+from .sayAll import initialize as sayAllInitialize
```
Comment (feerrenrut) [inline source/speech/__init__.py:147]: This means the order has changed subtly, before sayAll was imported after speechInitialize() was called. Does it matter?

Comment (seanbudd) [reply source/speech/__init__.py:147]: Matter in what way? The issue with uninstalling addons is still fixed.

Comment (feerrenrut) [reply source/speech/__init__.py:147]: I'm just pointing out that there is a subtle change in import / initialization order. Because the initialization code used to be at module level, it was run on import, now the import and initialization code is interleaved. There may be hard to predict consequences. It might be worth looking at that and trying to determine if there are any ways it could cause import problems. If we think there is a risk, then we can maintain the previous import / initialization order by moving the imports to within the package `initialize` method (prior to using `sayAllInitialize`)

Comment (seanbudd) [reply source/speech/__init__.py:147]: sayAll is no longer dependent on speech so I would think not. The imports all happen in the same order, it's just the initialization happens after sayAllInitialize instead of between `speechInitialize` and `sayAllInitialize`. My risk assessment is as follows:

Importing `sayAllInitialize` earlier, before initializing `speech`, could be a risk because:

1. importing `sayAll` might (eventually) depend on something in speech - this should not be a risk because the import order hasn't changed
1. importing `sayAll` might directly depend on something in speech being initialized - this is not a risk because all direct speech dependencies are dependency injected on initialisation. 
1. module level imports in `sayAll` could be affected if they are dependent on speech being initialized - this is not a risk as all the imports in `sayAll` are also in `speech` or `speech\__init__.py` (other than queueHandler, winKernel, which happen earlier elsewhere)

Initializing `speech` later, after importing `sayAll`, shouldn't be a risk because speech was never dependent on importing `sayAll`.

**Review by feerrenrut — DISMISSED** [review]
Please update the target to beta, and merge. We'll need to do another beta to master merge soon.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
The diff includes unrelated stuff from master (Eg the CLDR changes). You'll need to rebase.

**Review by feerrenrut — APPROVED** [review]
Thanks @seanbudd

**Comment by seanbudd** [comment]
@feerrenrut I'm unable to merge this
