### PR TITLE
Revert no longer classify (rich) edit classes as bad for UIA

### LINKED ISSUE #15330: UIA Adds "Rich Edit Control as name to rich edit objects
Regressed from #15314 

### Steps to reproduce:
1. In Explorer, open properties for NVDA executable
2. Go to the digital signatures tab
3. Select the signature and press details
4. Press the View certificate button.

### Actual behavior:
```
Certificate  dialog
General  property page  RichEdit Control
Private key exists note
Issuer Statement  button  Alt+s
```

### Expected behavior:
Don't announce "RichEdit Control"

```
Certificate  dialog
General  property page
Private key exists note
Issuer Statement  button  Alt+s
```

#### NVDA version:
alpha-28940,76530568

#### Windows version:
Windows 11 22H2

### LINKED ISSUE #15375: Edit controls in explorer fail when they have a native UIA implementation
Regression from #15314

### Steps to reproduce:
1. On a folder in Windows Explorer, open properties (alt+Enter)
2. Go to the security tab
3. Press the advanced button

### Actual behavior:
Read only edit boxes don't read. This is because they have an overlay in the explorer appModule that is bound to IAccessible rather than Edit.
```
error executing event: gainFocus on <NVDAObjects.Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAutoSelectDetectionUIAWindowNVDAObjectEditableIndentNav object at 0x07F71350> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 139, in setFocusObject
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 656, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1059, in _get_parent
AttributeError: 'Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAut' object has no attribute 'IAccessibleChildID'

```

### Expected behavior:
Edit boxes read correctly.

#### NVDA version:
2023.3 Beta branch

#### Windows version:
Windows 11 22H2

### Additional details
The code conflicting with UIA was introduced in 32a0f2298a, pr #8643. Cc @lukaszgo1 
Personally I'm tempted to remove this RTL and LTR workaround from the explorer appModule. While this will reintroduce these marks in the said edit boxes, removing the marks from the windowText is no viable solution to me as it will cause of by one errors when reporting the symbol or character under the caret.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Reintroduces #14285
Fixes #15375
Fixes #15330
Reverts #15314

### Summary of the issue:
In #15314, edit and rich edit classes were no longer classified as bad for UIA. This caused the following issues:

1. Read only edit fields in Explorer no longer read correctly, as they inherrit from both UIA and IAccessible
2. UIA adds a redundant name of RichEdit Control to RichEdit controls.

Generally spoken, removing these classes from the bad UIA classes list meant an API breaking change because Edit objects using UIA instead of legacy Edit support behave differently with regard to overriding and filtering texts, including LTR and RTL marks.

### Description of user facing changes
Reverted #15314. Most notably, the lag as reported in #14285 will unfortunately be reintroduced for now.

### Description of development approach
1. Re-add the bad UIA class names again.
2. Addressed issues in the explorer appmodule as pointed out in #15375.
    * Most notably, changed class inheritance from IAccessible to Edit
    * Added some small checks to overlay selection to ensure SysListView overlays won't be added on SysListView objects that don't use MSAA

### Testing strategy:
Tested str from #15375 and #15330

### Known issues with pull request:
None known

### Change log entries:
In pr

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

**Review by lukaszgo1 — APPROVED** [review]
LGTM

**Review by seanbudd — DISMISSED** [review]
Thanks @leonardder
