### PR TITLE
Fix issues with UIA (Rich)Edit implementations

### LINKED ISSUE #15330: UIA Adds "Rich Edit Control as name to rich edit objects
Regressed from #15314 

### Steps to reproduce:
1. In Explorer, open properties for NVDA executable
2. Go to the digital signatures tab
3. Select the signature and press details
4. Press the View certificate button.

### Actual behavior:
```
Certificate  dialog
General  property page  RichEdit Control
Private key exists note
Issuer Statement  button  Alt+s
```

### Expected behavior:
Don't announce "RichEdit Control"

```
Certificate  dialog
General  property page
Private key exists note
Issuer Statement  button  Alt+s
```

#### NVDA version:
alpha-28940,76530568

#### Windows version:
Windows 11 22H2

### LINKED ISSUE #15375: Edit controls in explorer fail when they have a native UIA implementation
Regression from #15314

### Steps to reproduce:
1. On a folder in Windows Explorer, open properties (alt+Enter)
2. Go to the security tab
3. Press the advanced button

### Actual behavior:
Read only edit boxes don't read. This is because they have an overlay in the explorer appModule that is bound to IAccessible rather than Edit.
```
error executing event: gainFocus on <NVDAObjects.Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAutoSelectDetectionUIAWindowNVDAObjectEditableIndentNav object at 0x07F71350> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 320, in executeEvent
  File "eventHandler.pyc", line 355, in doPreGainFocus
  File "api.pyc", line 139, in setFocusObject
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 656, in _get_container
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1059, in _get_parent
AttributeError: 'Dynamic_ReadOnlyEditBoxEditBaseEditableTextWithAut' object has no attribute 'IAccessibleChildID'

```

### Expected behavior:
Edit boxes read correctly.

#### NVDA version:
2023.3 Beta branch

#### Windows version:
Windows 11 22H2

### Additional details
The code conflicting with UIA was introduced in 32a0f2298a, pr #8643. Cc @lukaszgo1 
Personally I'm tempted to remove this RTL and LTR workaround from the explorer appModule. While this will reintroduce these marks in the said edit boxes, removing the marks from the windowText is no viable solution to me as it will cause of by one errors when reporting the symbol or character under the caret.

### PR DESCRIPTION
**Pull request by LeonarddeR**
### Link to issue number:
Fixes #15375
Fixes #15330 
Followup for #15314
Partially reverts #8643
Reopens #8361

### Summary of the issue:
#15314 no longer classified Edit and RichEdit classes as bad for UIA. This caused two problems:

1. Read only edit fields in Explorer no longer read correctly, as they inherrit from both UIA and IAccessible
2. UIA adds a redundant name of RichEdit Control to these objects.

While investigating these issues, I discovered that Windows 11 mimics the value in the name when renaming a file in Explorer.

### Description of user facing changes
1. No longer redundantly announce RichEdit Control for Rich Edit Controls.
2. Working edit fields in Explorer, with the expense of left-to-right and right-to-left marks being reported again when applicable (see below)
3. Suppress the name of the control when it copies the value.

### Description of development approach
1/3. I added a new EditUIA overlay class that inherrits from EditBase and UIA. This has a custom implementation for the name property.
2. Removed the ReadOnlyEditBox class from the explorer appmodule. Note, as this class is used in the appModule and only for specific purposes, I wouldn't classify this as API breaking and think we must remain pragmatic on this point.

### Testing strategy:
Tested str from fixed issues.

### Known issues with pull request:
Removing the ReadOnlyEditBox class from explorer partly reverts #8643. This means left-to-right and right-to-left marks are again being read in some edit controls. The problem with the fix in #8643 was that modified the windowText and therefore caused offset errors when navigating through these controls (i.e. if the text starts with one of these marks, caret reporting would be off by one and result in an error at the end of the line). This was acknowledged by @lukaszgo1 in https://github.com/nvaccess/nvda/issues/15375#issuecomment-1706545010. Note that at least in the security tab, there are focusabble fields like this.

### Change log entries:
None needed.

### Code Review Checklist:

- [x] Pull Request description:
  - description is up to date
  - change log entries
- [x] Testing:
  - Unit tests
  - System (end to end) tests
  - Manual testing
- [x] API is compatible with existing add-ons.
- [x] Documentation:
  - User Documentation
  - Developer / Technical Documentation
  - Context sensitive help for GUI changes
- [x] UX of all users considered:
  - Speech 
  - Braille
  - Low Vision
  - Different web browsers
  - Localization in other languages / culture than English
- [x] Security precautions taken.

### CODE REVIEW

File: source/NVDAObjects/UIA/__init__.py [hunk 1]
```diff
@@ -2438,3 +2437,20 @@ def _get_value(self) -> typing.Optional[str]:
...
 			val = ((val - minVal) / (maxVal - minVal)) * 100.0
 		return f"{round(val)}%"
+
+
+class EditUIA(EditBase, UIA):
+	"""Overlay class for Edit and RichEdit controls."""
+
+	def _get_name(self):
+		name = super().name
+		if name == "RichEdit Control":
```
Comment (lukaszgo1) [inline source/NVDAObjects/UIA/__init__.py:2447]: Have you tested that this name is not localized on non-English versions of Windows? If it tunrs out that it indeed is localized, perhaps we can just retrieve the IAccessible name with oleacc.

File: source/appModules/explorer.py [hunk 2]
```diff
@@ -224,16 +223,6 @@ def _get_value(self):
 			return value
 		return value.replace(CHAR_LTR_MARK,'').replace(CHAR_RTL_MARK,'')
 
-class ReadOnlyEditBox(IAccessible):
```
Comment (lukaszgo1) [inline source/appModules/explorer.py:227]: Note that this class is also imported in the `dllhost` appModule.

**Review by lukaszgo1 — COMMENTED** [review]
Let's hope that users won't be very annoyed with the re-introduction of these RTL and LTR symbols.

File: source/appModules/explorer.py (hunk 2 above)
Comment (seanbudd) [reply source/appModules/explorer.py:227]: this appears to be an API breaking change as well

**Comment by leonardder** [comment]
I"m sorry, this should have been a draft in the first place.
I'm going to change the approach and revert the removal from the bad UIA classes.

**Comment by leonardder** [comment]
superseded by #15381

File: source/NVDAObjects/UIA/__init__.py (hunk 1 above)
Comment (leonardder) [reply source/NVDAObjects/UIA/__init__.py:2447]: I have tested on a Dutch version of Windows that the name is indeed not localized. I considered using oleacc but that this would probably be quicker. Never mind though, only writing this down for future reference.
